apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootdemo
  labels:
    app: springbootdemo
spec:
  selector:
    matchLabels:
      app: springbootdemo
  template:
    metadata:
      labels:
        app: springbootdemo
    spec:
      containers:
      - name: springbootdemo
        image: realstore/springbootdemo:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /api/carts
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: springbootdemo
spec:
  type: NodePort
  selector:
    app: springbootdemo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32000
